### 날짜별 확진자수 최종 데이터프레임 읽기

In [1]:
import pandas as pd

df_confirmed = pd.read_csv('ex_datafile/COVID-19-master/final_df.csv')
df_confirmed

,Country_Region,1/01/2021,1/01/2022,1/01/2023,1/02/2021,1/02/2022,1/02/2023,1/03/2021,1/03/2022,1/03/2023,...,12/28/2022,12/29/2020,12/29/2021,12/29/2022,12/30/2020,12/30/2021,12/30/2022,12/31/2020,12/31/2021,12/31/2022
0,Afghanistan,52513,158107,207616,52586,158189,207627,52709,158183,207654,...,207493,52147,158037,207511,52330,158056,207550,52330,158084,207559
1,Albania,58316,210224,333811,58991,210885,333812,59438,210885,333812,...,333776,57146,208899,333776,57727,208899,333806,58316,210224,333806
2,Algeria,99897,218818,271229,100159,219159,271229,100408,219532,271230,...,271208,98988,217647,271217,99311,218037,271223,99610,218432,271228
3,Andorra,8117,23740,47751,8166,23740,47751,8192,24502,47751,...,47751,7919,22823,47751,7983,23122,47751,8049,23740,47751
4,Angola,17568,82398,105095,17608,82920,105095,17642,83764,105095,...,105095,17371,78475,105095,17433,79871,105095,17553,81593,105095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,West Bank and Gaza,139223,469748,703228,140287,469748,703228,141219,469748,703228,...,703228,135459,469748,703228,136736,469748,703228,138004,469748,703228
197,Winter Olympics 2022,0,0,535,0,0,535,0,0,535,...,535,0,0,535,0,0,535,0,0,535
198,Yemen,2101,10127,11945,2101,10130,11945,2101,10138,11945,...,11945,2096,10125,11945,2097,10126,11945,2099,10126,11945
199,Zambia,20997,257948,334629,21230,259677,334661,21582,261221,334695,...,334196,20177,243638,334294,20462,249193,334425,20725,254274,334425
200,Zimbabwe,14084,214214,259981,14491,214214,259981,15265,216087,259981,...,259981,13325,207548,259981,13625,211728,259981,13867,213258,259981

In [2]:
df_confirmed.shape

(201, 1144)

### 국가명과 iso2 매칭 테이블 읽기(country_info)
- iso2 컬럼값으로 https://www.countryflags.com/ 에서 제공하는 국기 이미지 링크를 얻을 수 있다.